"""add ledger_entries table

Revision ID: 0a8896c85eff
Revises: 2f1ec3b945c7
Create Date: 2026-03-16 18:15:06.225996
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8896c85eff'
down_revision: Union[str, None] = '2f1ec3b945c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tds_section', sa.String(length=10), nullable=True),
    sa.Column('tcs_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('fy_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_fy', 'ledger_entries', ['fy_id'], unique=False)
    op.create_index('ix_ledger_party', 'ledger_entries', ['party_type', 'party_id', 'entry_date'], unique=False)
    op.create_index('ix_ledger_ref', 'ledger_entries', ['reference_type', 'reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_ref', table_name='ledger_entries')
    op.drop_index('ix_ledger_party', table_name='ledger_entries')
    op.drop_index('ix_ledger_fy', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
