"""add_color_no_to_color

Revision ID: 2a1bf32421db
Revises: 9530f3b5bc2b
Create Date: 2026-02-18 12:30:14.117674
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1bf32421db'
down_revision: Union[str, None] = '9530f3b5bc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colors', sa.Column('color_no', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_colors_color_no'), 'colors', ['color_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_colors_color_no'), table_name='colors')
    op.drop_column('colors', 'color_no')
    # ### end Alembic commands ###
