"""Add Customer model, enrich Supplier+VAParty, customer_id FK on Order

Revision ID: 2f1ec3b945c7
Revises: ca193c1c4572
Create Date: 2026-03-16 16:30:04.572692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1ec3b945c7'
down_revision: Union[str, None] = 'ca193c1c4572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_alt', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('gst_no', sa.String(length=15), nullable=True),
    sa.Column('gst_type', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('aadhar_no', sa.String(length=12), nullable=True),
    sa.Column('due_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_type', sa.String(length=10), nullable=True),
    sa.Column('tds_applicable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tds_section', sa.String(length=10), nullable=True),
    sa.Column('tcs_applicable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tcs_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tcs_section', sa.String(length=10), nullable=True),
    sa.Column('broker', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    from app.database import is_postgresql
    if is_postgresql():
        op.add_column('orders', sa.Column('customer_id', sa.Uuid(), nullable=True))
        op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
        op.create_foreign_key(op.f('fk_orders_customer_id_customers'), 'orders', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    else:
        with op.batch_alter_table('orders') as batch_op:
            batch_op.add_column(sa.Column('customer_id', sa.Uuid(), nullable=True))
            batch_op.create_index(op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
            batch_op.create_foreign_key(op.f('fk_orders_customer_id_customers'), 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.add_column('suppliers', sa.Column('phone_alt', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('gst_type', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('state_code', sa.String(length=2), nullable=True))
    op.add_column('suppliers', sa.Column('aadhar_no', sa.String(length=12), nullable=True))
    op.add_column('suppliers', sa.Column('due_days', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('suppliers', sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('suppliers', sa.Column('balance_type', sa.String(length=10), nullable=True))
    op.add_column('suppliers', sa.Column('tds_applicable', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('suppliers', sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('suppliers', sa.Column('tds_section', sa.String(length=10), nullable=True))
    op.add_column('suppliers', sa.Column('msme_type', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('msme_reg_no', sa.String(length=30), nullable=True))
    op.add_column('suppliers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('va_parties', sa.Column('contact_person', sa.String(length=200), nullable=True))
    op.add_column('va_parties', sa.Column('phone_alt', sa.String(length=20), nullable=True))
    op.add_column('va_parties', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('va_parties', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('va_parties', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('va_parties', sa.Column('pin_code', sa.String(length=10), nullable=True))
    op.add_column('va_parties', sa.Column('gst_type', sa.String(length=20), nullable=True))
    op.add_column('va_parties', sa.Column('state_code', sa.String(length=2), nullable=True))
    op.add_column('va_parties', sa.Column('pan_no', sa.String(length=10), nullable=True))
    op.add_column('va_parties', sa.Column('aadhar_no', sa.String(length=12), nullable=True))
    op.add_column('va_parties', sa.Column('due_days', sa.Integer(), nullable=True))
    op.add_column('va_parties', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('va_parties', sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('va_parties', sa.Column('balance_type', sa.String(length=10), nullable=True))
    op.add_column('va_parties', sa.Column('tds_applicable', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('va_parties', sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('va_parties', sa.Column('tds_section', sa.String(length=10), nullable=True))
    op.add_column('va_parties', sa.Column('msme_type', sa.String(length=20), nullable=True))
    op.add_column('va_parties', sa.Column('msme_reg_no', sa.String(length=30), nullable=True))
    op.add_column('va_parties', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('va_parties', 'notes')
    op.drop_column('va_parties', 'msme_reg_no')
    op.drop_column('va_parties', 'msme_type')
    op.drop_column('va_parties', 'tds_section')
    op.drop_column('va_parties', 'tds_rate')
    op.drop_column('va_parties', 'tds_applicable')
    op.drop_column('va_parties', 'balance_type')
    op.drop_column('va_parties', 'opening_balance')
    op.drop_column('va_parties', 'credit_limit')
    op.drop_column('va_parties', 'due_days')
    op.drop_column('va_parties', 'aadhar_no')
    op.drop_column('va_parties', 'pan_no')
    op.drop_column('va_parties', 'state_code')
    op.drop_column('va_parties', 'gst_type')
    op.drop_column('va_parties', 'pin_code')
    op.drop_column('va_parties', 'state')
    op.drop_column('va_parties', 'address')
    op.drop_column('va_parties', 'email')
    op.drop_column('va_parties', 'phone_alt')
    op.drop_column('va_parties', 'contact_person')
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'msme_reg_no')
    op.drop_column('suppliers', 'msme_type')
    op.drop_column('suppliers', 'tds_section')
    op.drop_column('suppliers', 'tds_rate')
    op.drop_column('suppliers', 'tds_applicable')
    op.drop_column('suppliers', 'balance_type')
    op.drop_column('suppliers', 'opening_balance')
    op.drop_column('suppliers', 'credit_limit')
    op.drop_column('suppliers', 'due_days')
    op.drop_column('suppliers', 'aadhar_no')
    op.drop_column('suppliers', 'state_code')
    op.drop_column('suppliers', 'gst_type')
    op.drop_column('suppliers', 'phone_alt')
    op.drop_constraint(op.f('fk_orders_customer_id_customers'), 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'customer_id')
    op.drop_table('customers')
    # ### end Alembic commands ###
