"""s76_fy_closing_snapshot

Revision ID: 3e78791f67a1
Revises: d5de97f3daf8
Create Date: 2026-03-17 02:28:12.504406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e78791f67a1'
down_revision: Union[str, None] = 'd5de97f3daf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_batch_assignments_tailor_id_users', 'batch_assignments', type_='foreignkey')
    op.drop_constraint('fk_batch_assignments_assigned_by_users', 'batch_assignments', type_='foreignkey')
    op.drop_constraint('fk_batch_assignments_checker_id_users', 'batch_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_batch_assignments_checker_id_users'), 'batch_assignments', 'users', ['checker_id'], ['id'], referent_schema='public')
    op.create_foreign_key(op.f('fk_batch_assignments_assigned_by_users'), 'batch_assignments', 'users', ['assigned_by'], ['id'], referent_schema='public')
    op.create_foreign_key(op.f('fk_batch_assignments_tailor_id_users'), 'batch_assignments', 'users', ['tailor_id'], ['id'], referent_schema='public')
    op.drop_constraint('fk_batch_challans_created_by_id_users', 'batch_challans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_batch_challans_created_by_id_users'), 'batch_challans', 'users', ['created_by_id'], ['id'], referent_schema='public')
    op.drop_constraint('fk_batch_processing_created_by_id_users', 'batch_processing', type_='foreignkey')
    op.create_foreign_key(op.f('fk_batch_processing_created_by_id_users'), 'batch_processing', 'users', ['created_by_id'], ['id'], referent_schema='public')
    op.drop_constraint('fk_batch_roll_consumption_cut_by_users', 'batch_roll_consumption', type_='foreignkey')
    op.create_foreign_key(op.f('fk_batch_roll_consumption_cut_by_users'), 'batch_roll_consumption', 'users', ['cut_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_batches_created_by_users', 'batches', type_='foreignkey')
    op.drop_constraint('fk_batches_packed_by_users', 'batches', type_='foreignkey')
    op.drop_constraint('fk_batches_checked_by_users', 'batches', type_='foreignkey')
    op.create_foreign_key(op.f('fk_batches_checked_by_users'), 'batches', 'users', ['checked_by'], ['id'], referent_schema='public')
    op.create_foreign_key(op.f('fk_batches_packed_by_users'), 'batches', 'users', ['packed_by'], ['id'], referent_schema='public')
    op.create_foreign_key(op.f('fk_batches_created_by_users'), 'batches', 'users', ['created_by'], ['id'], referent_schema='public')
    op.add_column('financial_years', sa.Column('closing_snapshot', sa.JSON(), nullable=True))
    op.drop_constraint('fk_financial_years_closed_by_users', 'financial_years', type_='foreignkey')
    op.create_foreign_key(op.f('fk_financial_years_closed_by_users'), 'financial_years', 'users', ['closed_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_inventory_events_performed_by_users', 'inventory_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_events_performed_by_users'), 'inventory_events', 'users', ['performed_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_invoices_created_by_users', 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_created_by_users'), 'invoices', 'users', ['created_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_job_challans_created_by_id_users', 'job_challans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_challans_created_by_id_users'), 'job_challans', 'users', ['created_by_id'], ['id'], referent_schema='public')
    op.drop_constraint('fk_lots_created_by_users', 'lots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lots_created_by_users'), 'lots', 'users', ['created_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_orders_created_by_users', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_created_by_users'), 'orders', 'users', ['created_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_rolls_received_by_users', 'rolls', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rolls_received_by_users'), 'rolls', 'users', ['received_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_supplier_invoices_received_by_users', 'supplier_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_supplier_invoices_received_by_users'), 'supplier_invoices', 'users', ['received_by'], ['id'], referent_schema='public')
    op.drop_constraint('fk_user_companies_company_id_companies', 'user_companies', type_='foreignkey')
    op.drop_constraint('fk_user_companies_user_id_users', 'user_companies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_companies_user_id_users'), 'user_companies', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_companies_company_id_companies'), 'user_companies', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_role_id_roles'), 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_role_id_roles'), 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(op.f('fk_user_companies_company_id_companies'), 'user_companies', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_companies_user_id_users'), 'user_companies', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_user_companies_user_id_users', 'user_companies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_companies_company_id_companies', 'user_companies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_supplier_invoices_received_by_users'), 'supplier_invoices', type_='foreignkey')
    op.create_foreign_key('fk_supplier_invoices_received_by_users', 'supplier_invoices', 'users', ['received_by'], ['id'])
    op.drop_constraint(op.f('fk_rolls_received_by_users'), 'rolls', type_='foreignkey')
    op.create_foreign_key('fk_rolls_received_by_users', 'rolls', 'users', ['received_by'], ['id'])
    op.drop_constraint(op.f('fk_orders_created_by_users'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_created_by_users', 'orders', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_lots_created_by_users'), 'lots', type_='foreignkey')
    op.create_foreign_key('fk_lots_created_by_users', 'lots', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_job_challans_created_by_id_users'), 'job_challans', type_='foreignkey')
    op.create_foreign_key('fk_job_challans_created_by_id_users', 'job_challans', 'users', ['created_by_id'], ['id'])
    op.drop_constraint(op.f('fk_invoices_created_by_users'), 'invoices', type_='foreignkey')
    op.create_foreign_key('fk_invoices_created_by_users', 'invoices', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_inventory_events_performed_by_users'), 'inventory_events', type_='foreignkey')
    op.create_foreign_key('fk_inventory_events_performed_by_users', 'inventory_events', 'users', ['performed_by'], ['id'])
    op.drop_constraint(op.f('fk_financial_years_closed_by_users'), 'financial_years', type_='foreignkey')
    op.create_foreign_key('fk_financial_years_closed_by_users', 'financial_years', 'users', ['closed_by'], ['id'])
    op.drop_column('financial_years', 'closing_snapshot')
    op.drop_constraint(op.f('fk_batches_created_by_users'), 'batches', type_='foreignkey')
    op.drop_constraint(op.f('fk_batches_packed_by_users'), 'batches', type_='foreignkey')
    op.drop_constraint(op.f('fk_batches_checked_by_users'), 'batches', type_='foreignkey')
    op.create_foreign_key('fk_batches_checked_by_users', 'batches', 'users', ['checked_by'], ['id'])
    op.create_foreign_key('fk_batches_packed_by_users', 'batches', 'users', ['packed_by'], ['id'])
    op.create_foreign_key('fk_batches_created_by_users', 'batches', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_batch_roll_consumption_cut_by_users'), 'batch_roll_consumption', type_='foreignkey')
    op.create_foreign_key('fk_batch_roll_consumption_cut_by_users', 'batch_roll_consumption', 'users', ['cut_by'], ['id'])
    op.drop_constraint(op.f('fk_batch_processing_created_by_id_users'), 'batch_processing', type_='foreignkey')
    op.create_foreign_key('fk_batch_processing_created_by_id_users', 'batch_processing', 'users', ['created_by_id'], ['id'])
    op.drop_constraint(op.f('fk_batch_challans_created_by_id_users'), 'batch_challans', type_='foreignkey')
    op.create_foreign_key('fk_batch_challans_created_by_id_users', 'batch_challans', 'users', ['created_by_id'], ['id'])
    op.drop_constraint(op.f('fk_batch_assignments_tailor_id_users'), 'batch_assignments', type_='foreignkey')
    op.drop_constraint(op.f('fk_batch_assignments_assigned_by_users'), 'batch_assignments', type_='foreignkey')
    op.drop_constraint(op.f('fk_batch_assignments_checker_id_users'), 'batch_assignments', type_='foreignkey')
    op.create_foreign_key('fk_batch_assignments_checker_id_users', 'batch_assignments', 'users', ['checker_id'], ['id'])
    op.create_foreign_key('fk_batch_assignments_assigned_by_users', 'batch_assignments', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key('fk_batch_assignments_tailor_id_users', 'batch_assignments', 'users', ['tailor_id'], ['id'])
    # ### end Alembic commands ###
