"""add_challan_no_and_sr_no_to_rolls

Revision ID: 6f0c0d32405c
Revises: a1f51406dec0
Create Date: 2026-02-17 23:59:06.903601
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0c0d32405c'
down_revision: Union[str, None] = 'a1f51406dec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolls', sa.Column('supplier_challan_no', sa.String(length=50), nullable=True))
    op.add_column('rolls', sa.Column('sr_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rolls', 'sr_no')
    op.drop_column('rolls', 'supplier_challan_no')
    # ### end Alembic commands ###
