"""sku_enrichment_hsn_gst_mrp_sale_rate_unit

Revision ID: 839de8e2386a
Revises: 0a8896c85eff
Create Date: 2026-03-16 18:30:02.484874
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839de8e2386a'
down_revision: Union[str, None] = '0a8896c85eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('hsn_code', sa.String(length=8), nullable=True))
    op.add_column('skus', sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('skus', sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('skus', sa.Column('sale_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('skus', sa.Column('unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'unit')
    op.drop_column('skus', 'sale_rate')
    op.drop_column('skus', 'mrp')
    op.drop_column('skus', 'gst_percent')
    op.drop_column('skus', 'hsn_code')
    # ### end Alembic commands ###
