"""add_broker_hsn_to_supplier_panna_gsm_to_roll

Revision ID: 9530f3b5bc2b
Revises: 6f0c0d32405c
Create Date: 2026-02-18 12:06:00.484337
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9530f3b5bc2b'
down_revision: Union[str, None] = '6f0c0d32405c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolls', sa.Column('panna', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('rolls', sa.Column('gsm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('suppliers', sa.Column('broker', sa.String(length=200), nullable=True))
    op.add_column('suppliers', sa.Column('hsn_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'hsn_code')
    op.drop_column('suppliers', 'broker')
    op.drop_column('rolls', 'gsm')
    op.drop_column('rolls', 'panna')
    # ### end Alembic commands ###
