"""add_master_tables

Revision ID: a1f51406dec0
Revises: d865522310db
Create Date: 2026-02-17 10:44:38.906823
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f51406dec0'
down_revision: Union[str, None] = 'd865522310db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_index(op.f('ix_colors_code'), 'colors', ['code'], unique=True)
    op.create_table('fabrics',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabrics'))
    )
    op.create_index(op.f('ix_fabrics_code'), 'fabrics', ['code'], unique=True)
    op.create_table('product_types',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_types'))
    )
    op.create_index(op.f('ix_product_types_code'), 'product_types', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_types_code'), table_name='product_types')
    op.drop_table('product_types')
    op.drop_index(op.f('ix_fabrics_code'), table_name='fabrics')
    op.drop_table('fabrics')
    op.drop_index(op.f('ix_colors_code'), table_name='colors')
    op.drop_table('colors')
    # ### end Alembic commands ###
