"""s76_baseline_public_tenant_split_32_tables

Revision ID: d5de97f3daf8
Revises: 
Create Date: 2026-03-17 00:52:07.822970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5de97f3daf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('color_no', sa.Integer(), nullable=True),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_index(op.f('ix_colors_code'), 'colors', ['code'], unique=True)
    op.create_index(op.f('ix_colors_color_no'), 'colors', ['color_no'], unique=True)
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_alt', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('gst_no', sa.String(length=15), nullable=True),
    sa.Column('gst_type', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('aadhar_no', sa.String(length=12), nullable=True),
    sa.Column('due_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_type', sa.String(length=10), nullable=True),
    sa.Column('tds_applicable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tds_section', sa.String(length=10), nullable=True),
    sa.Column('tcs_applicable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tcs_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tcs_section', sa.String(length=10), nullable=True),
    sa.Column('broker', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('fabrics',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabrics'))
    )
    op.create_index(op.f('ix_fabrics_code'), 'fabrics', ['code'], unique=True)
    op.create_table('product_types',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_types'))
    )
    op.create_index(op.f('ix_product_types_code'), 'product_types', ['code'], unique=True)
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('schema_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('gst_no', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account', sa.String(length=30), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=11), nullable=True),
    sa.Column('bank_branch', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('schema_name', name=op.f('uq_companies_schema_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug')),
    schema='public'
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name')),
    schema='public'
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_alt', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=6), nullable=True),
    sa.Column('gst_no', sa.String(length=15), nullable=True),
    sa.Column('gst_type', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('aadhar_no', sa.String(length=12), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('due_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_type', sa.String(length=10), nullable=True),
    sa.Column('tds_applicable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tds_section', sa.String(length=10), nullable=True),
    sa.Column('msme_type', sa.String(length=20), nullable=True),
    sa.Column('msme_reg_no', sa.String(length=30), nullable=True),
    sa.Column('broker', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('va_parties',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_alt', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('gst_no', sa.String(length=20), nullable=True),
    sa.Column('gst_type', sa.String(length=20), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('aadhar_no', sa.String(length=12), nullable=True),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('due_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_type', sa.String(length=10), nullable=True),
    sa.Column('tds_applicable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tds_section', sa.String(length=10), nullable=True),
    sa.Column('msme_type', sa.String(length=20), nullable=True),
    sa.Column('msme_reg_no', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_va_parties'))
    )
    op.create_table('value_additions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=4), nullable=False),
    sa.Column('applicable_to', sa.String(length=20), server_default='both', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_value_additions'))
    )
    op.create_index(op.f('ix_value_additions_short_code'), 'value_additions', ['short_code'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    schema='public'
    )
    op.create_table('skus',
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('color_id', sa.Uuid(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hsn_code', sa.String(length=8), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_skus_color_id_colors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skus')),
    sa.UniqueConstraint('sku_code', name=op.f('uq_skus_sku_code'))
    )
    op.create_index(op.f('ix_skus_color_id'), 'skus', ['color_id'], unique=False)
    op.create_table('batch_challans',
    sa.Column('challan_no', sa.String(length=30), nullable=False),
    sa.Column('va_party_id', sa.Uuid(), nullable=True),
    sa.Column('value_addition_id', sa.Uuid(), nullable=False),
    sa.Column('total_pieces', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sent_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['public.users.id'], name=op.f('fk_batch_challans_created_by_id_users')),
    sa.ForeignKeyConstraint(['va_party_id'], ['va_parties.id'], name=op.f('fk_batch_challans_va_party_id_va_parties')),
    sa.ForeignKeyConstraint(['value_addition_id'], ['value_additions.id'], name=op.f('fk_batch_challans_value_addition_id_value_additions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_challans'))
    )
    op.create_index(op.f('ix_batch_challans_challan_no'), 'batch_challans', ['challan_no'], unique=True)
    op.create_index(op.f('ix_batch_challans_status'), 'batch_challans', ['status'], unique=False)
    op.create_index(op.f('ix_batch_challans_va_party_id'), 'batch_challans', ['va_party_id'], unique=False)
    op.create_index(op.f('ix_batch_challans_value_addition_id'), 'batch_challans', ['value_addition_id'], unique=False)
    op.create_table('financial_years',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['public.users.id'], name=op.f('fk_financial_years_closed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_years')),
    sa.UniqueConstraint('code', name=op.f('uq_financial_years_code'))
    )
    op.create_table('inventory_state',
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('total_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_inventory_state_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_state')),
    sa.UniqueConstraint('sku_id', name=op.f('uq_inventory_state_sku_id'))
    )
    op.create_table('job_challans',
    sa.Column('challan_no', sa.String(length=30), nullable=False),
    sa.Column('value_addition_id', sa.Uuid(), nullable=False),
    sa.Column('va_party_id', sa.Uuid(), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['public.users.id'], name=op.f('fk_job_challans_created_by_id_users')),
    sa.ForeignKeyConstraint(['va_party_id'], ['va_parties.id'], name=op.f('fk_job_challans_va_party_id_va_parties')),
    sa.ForeignKeyConstraint(['value_addition_id'], ['value_additions.id'], name=op.f('fk_job_challans_value_addition_id_value_additions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_challans'))
    )
    op.create_index(op.f('ix_job_challans_challan_no'), 'job_challans', ['challan_no'], unique=True)
    op.create_index(op.f('ix_job_challans_status'), 'job_challans', ['status'], unique=False)
    op.create_index(op.f('ix_job_challans_va_party_id'), 'job_challans', ['va_party_id'], unique=False)
    op.create_table('lots',
    sa.Column('lot_code', sa.String(length=50), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('lot_date', sa.Date(), nullable=False),
    sa.Column('design_no', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=10), server_default='BLS', nullable=False),
    sa.Column('standard_palla_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('standard_palla_meter', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('default_size_pattern', sa.JSON(), nullable=False),
    sa.Column('pieces_per_palla', sa.Integer(), nullable=False),
    sa.Column('total_pallas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_pieces', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'cutting', 'distributed')", name=op.f('ck_lots_valid_status')),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], name=op.f('fk_lots_created_by_users')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_lots_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lots')),
    sa.UniqueConstraint('lot_code', name=op.f('uq_lots_lot_code'))
    )
    op.create_index(op.f('ix_lots_sku_id'), 'lots', ['sku_id'], unique=False)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_table('user_companies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['public.companies.id'], name=op.f('fk_user_companies_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name=op.f('fk_user_companies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_companies')),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company'),
    schema='public'
    )
    op.create_table('batches',
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('piece_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('color_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_qty', sa.Integer(), nullable=True),
    sa.Column('rejected_qty', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.Uuid(), nullable=True),
    sa.Column('packed_by', sa.Uuid(), nullable=True),
    sa.Column('packed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pack_reference', sa.String(length=50), nullable=True),
    sa.Column('color_qc', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'assigned', 'in_progress', 'submitted', 'checked', 'packing', 'packed')", name=op.f('ck_batches_valid_status')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_batches_positive_quantity')),
    sa.ForeignKeyConstraint(['checked_by'], ['public.users.id'], name=op.f('fk_batches_checked_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], name=op.f('fk_batches_created_by_users')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_batches_lot_id_lots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['packed_by'], ['public.users.id'], name=op.f('fk_batches_packed_by_users')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_batches_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('batch_code', name=op.f('uq_batches_batch_code'))
    )
    op.create_index(op.f('ix_batches_lot_id'), 'batches', ['lot_id'], unique=False)
    op.create_index(op.f('ix_batches_size'), 'batches', ['size'], unique=False)
    op.create_index(op.f('ix_batches_sku_id'), 'batches', ['sku_id'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tds_section', sa.String(length=10), nullable=True),
    sa.Column('tcs_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('fy_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fy_id'], ['financial_years.id'], name=op.f('fk_ledger_entries_fy_id_financial_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_fy', 'ledger_entries', ['fy_id'], unique=False)
    op.create_index('ix_ledger_party', 'ledger_entries', ['party_type', 'party_id', 'entry_date'], unique=False)
    op.create_index('ix_ledger_ref', 'ledger_entries', ['reference_type', 'reference_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_order_ref', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fy_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], name=op.f('fk_orders_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fy_id'], ['financial_years.id'], name=op.f('fk_orders_fy_id_financial_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_fy_id'), 'orders', ['fy_id'], unique=False)
    op.create_index(op.f('ix_orders_source'), 'orders', ['source'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('supplier_invoices',
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('challan_no', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fy_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fy_id'], ['financial_years.id'], name=op.f('fk_supplier_invoices_fy_id_financial_years')),
    sa.ForeignKeyConstraint(['received_by'], ['public.users.id'], name=op.f('fk_supplier_invoices_received_by_users')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_invoices_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_invoices'))
    )
    op.create_index(op.f('ix_supplier_invoices_fy_id'), 'supplier_invoices', ['fy_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_invoice_no'), 'supplier_invoices', ['invoice_no'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_sr_no'), 'supplier_invoices', ['sr_no'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_supplier_id'), 'supplier_invoices', ['supplier_id'], unique=False)
    op.create_table('batch_assignments',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('tailor_id', sa.Uuid(), nullable=False),
    sa.Column('checker_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['public.users.id'], name=op.f('fk_batch_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_assignments_batch_id_batches')),
    sa.ForeignKeyConstraint(['checker_id'], ['public.users.id'], name=op.f('fk_batch_assignments_checker_id_users')),
    sa.ForeignKeyConstraint(['tailor_id'], ['public.users.id'], name=op.f('fk_batch_assignments_tailor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_assignments'))
    )
    op.create_index(op.f('ix_batch_assignments_batch_id'), 'batch_assignments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_assignments_tailor_id'), 'batch_assignments', ['tailor_id'], unique=False)
    op.create_table('batch_processing',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('batch_challan_id', sa.Uuid(), nullable=False),
    sa.Column('value_addition_id', sa.Uuid(), nullable=False),
    sa.Column('pieces_sent', sa.Integer(), nullable=False),
    sa.Column('pieces_received', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pieces_sent > 0', name=op.f('ck_batch_processing_positive_pieces_sent')),
    sa.ForeignKeyConstraint(['batch_challan_id'], ['batch_challans.id'], name=op.f('fk_batch_processing_batch_challan_id_batch_challans')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_processing_batch_id_batches')),
    sa.ForeignKeyConstraint(['created_by_id'], ['public.users.id'], name=op.f('fk_batch_processing_created_by_id_users')),
    sa.ForeignKeyConstraint(['value_addition_id'], ['value_additions.id'], name=op.f('fk_batch_processing_value_addition_id_value_additions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_processing'))
    )
    op.create_index(op.f('ix_batch_processing_batch_challan_id'), 'batch_processing', ['batch_challan_id'], unique=False)
    op.create_index(op.f('ix_batch_processing_batch_id'), 'batch_processing', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_processing_status'), 'batch_processing', ['status'], unique=False)
    op.create_index(op.f('ix_batch_processing_value_addition_id'), 'batch_processing', ['value_addition_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fy_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], name=op.f('fk_invoices_created_by_users')),
    sa.ForeignKeyConstraint(['fy_id'], ['financial_years.id'], name=op.f('fk_invoices_fy_id_financial_years')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_index(op.f('ix_invoices_fy_id'), 'invoices', ['fy_id'], unique=False)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fulfilled_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_order_items_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_sku_id'), 'order_items', ['sku_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_code', sa.String(length=50), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('external_order_ref', sa.String(length=100), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reservations_order_id_orders')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_reservations_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('reservation_code', name=op.f('uq_reservations_reservation_code'))
    )
    op.create_index(op.f('ix_reservations_sku_id'), 'reservations', ['sku_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_table('rolls',
    sa.Column('roll_code', sa.String(length=80), nullable=False),
    sa.Column('fabric_type', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('color_id', sa.Uuid(), nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('remaining_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('current_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='kg', nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='in_stock', nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=50), nullable=True),
    sa.Column('supplier_challan_no', sa.String(length=50), nullable=True),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=True),
    sa.Column('sr_no', sa.String(length=20), nullable=True),
    sa.Column('panna', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gsm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fy_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_stock', 'sent_for_processing', 'in_cutting', 'remnant')", name=op.f('ck_rolls_valid_status')),
    sa.CheckConstraint('remaining_weight >= 0', name=op.f('ck_rolls_non_negative_remaining')),
    sa.CheckConstraint('total_weight > 0', name=op.f('ck_rolls_positive_weight')),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_rolls_color_id_colors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fy_id'], ['financial_years.id'], name=op.f('fk_rolls_fy_id_financial_years')),
    sa.ForeignKeyConstraint(['received_by'], ['public.users.id'], name=op.f('fk_rolls_received_by_users')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_rolls_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], name=op.f('fk_rolls_supplier_invoice_id_supplier_invoices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rolls')),
    sa.UniqueConstraint('roll_code', name=op.f('uq_rolls_roll_code'))
    )
    op.create_index(op.f('ix_rolls_color_id'), 'rolls', ['color_id'], unique=False)
    op.create_index(op.f('ix_rolls_fy_id'), 'rolls', ['fy_id'], unique=False)
    op.create_index(op.f('ix_rolls_sr_no'), 'rolls', ['sr_no'], unique=False)
    op.create_index(op.f('ix_rolls_status'), 'rolls', ['status'], unique=False)
    op.create_index(op.f('ix_rolls_supplier_id'), 'rolls', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_rolls_supplier_invoice_id'), 'rolls', ['supplier_invoice_id'], unique=False)
    op.create_index(op.f('ix_rolls_supplier_invoice_no'), 'rolls', ['supplier_invoice_no'], unique=False)
    op.create_table('batch_roll_consumption',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('roll_id', sa.Uuid(), nullable=False),
    sa.Column('pieces_cut', sa.Integer(), nullable=False),
    sa.Column('length_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_by', sa.Uuid(), nullable=True),
    sa.Column('cut_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_roll_consumption_batch_id_batches')),
    sa.ForeignKeyConstraint(['cut_by'], ['public.users.id'], name=op.f('fk_batch_roll_consumption_cut_by_users')),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_batch_roll_consumption_roll_id_rolls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_roll_consumption'))
    )
    op.create_index(op.f('ix_batch_roll_consumption_batch_id'), 'batch_roll_consumption', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_roll_consumption_roll_id'), 'batch_roll_consumption', ['roll_id'], unique=False)
    op.create_table('inventory_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('roll_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['public.users.id'], name=op.f('fk_inventory_events_performed_by_users')),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_inventory_events_roll_id_rolls')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_inventory_events_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_inventory_events_event_id'))
    )
    op.create_index(op.f('ix_inventory_events_event_type'), 'inventory_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_inventory_events_performed_at'), 'inventory_events', ['performed_at'], unique=False)
    op.create_index(op.f('ix_inventory_events_roll_id'), 'inventory_events', ['roll_id'], unique=False)
    op.create_index(op.f('ix_inventory_events_sku_id'), 'inventory_events', ['sku_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_invoice_items_batch_id_batches')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_invoice_items_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('lot_rolls',
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('roll_id', sa.Uuid(), nullable=False),
    sa.Column('palla_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('num_pallas', sa.Integer(), nullable=False),
    sa.Column('weight_used', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('waste_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('size_pattern', sa.JSON(), nullable=True),
    sa.Column('pieces_from_roll', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_lot_rolls_lot_id_lots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_lot_rolls_roll_id_rolls'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot_rolls'))
    )
    op.create_index(op.f('ix_lot_rolls_lot_id'), 'lot_rolls', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_rolls_roll_id'), 'lot_rolls', ['roll_id'], unique=False)
    op.create_table('roll_processing',
    sa.Column('roll_id', sa.Uuid(), nullable=False),
    sa.Column('value_addition_id', sa.Uuid(), nullable=False),
    sa.Column('va_party_id', sa.Uuid(), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('weight_before', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('weight_after', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('length_before', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('length_after', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processing_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('job_challan_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_challan_id'], ['job_challans.id'], name=op.f('fk_roll_processing_job_challan_id_job_challans')),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_roll_processing_roll_id_rolls')),
    sa.ForeignKeyConstraint(['va_party_id'], ['va_parties.id'], name=op.f('fk_roll_processing_va_party_id_va_parties')),
    sa.ForeignKeyConstraint(['value_addition_id'], ['value_additions.id'], name=op.f('fk_roll_processing_value_addition_id_value_additions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roll_processing'))
    )
    op.create_index(op.f('ix_roll_processing_job_challan_id'), 'roll_processing', ['job_challan_id'], unique=False)
    op.create_index(op.f('ix_roll_processing_roll_id'), 'roll_processing', ['roll_id'], unique=False)
    op.create_index(op.f('ix_roll_processing_va_party_id'), 'roll_processing', ['va_party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roll_processing_va_party_id'), table_name='roll_processing')
    op.drop_index(op.f('ix_roll_processing_roll_id'), table_name='roll_processing')
    op.drop_index(op.f('ix_roll_processing_job_challan_id'), table_name='roll_processing')
    op.drop_table('roll_processing')
    op.drop_index(op.f('ix_lot_rolls_roll_id'), table_name='lot_rolls')
    op.drop_index(op.f('ix_lot_rolls_lot_id'), table_name='lot_rolls')
    op.drop_table('lot_rolls')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_inventory_events_sku_id'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_roll_id'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_performed_at'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_event_type'), table_name='inventory_events')
    op.drop_table('inventory_events')
    op.drop_index(op.f('ix_batch_roll_consumption_roll_id'), table_name='batch_roll_consumption')
    op.drop_index(op.f('ix_batch_roll_consumption_batch_id'), table_name='batch_roll_consumption')
    op.drop_table('batch_roll_consumption')
    op.drop_index(op.f('ix_rolls_supplier_invoice_no'), table_name='rolls')
    op.drop_index(op.f('ix_rolls_supplier_invoice_id'), table_name='rolls')
    op.drop_index(op.f('ix_rolls_supplier_id'), table_name='rolls')
    op.drop_index(op.f('ix_rolls_status'), table_name='rolls')
    op.drop_index(op.f('ix_rolls_sr_no'), table_name='rolls')
    op.drop_index(op.f('ix_rolls_fy_id'), table_name='rolls')
    op.drop_index(op.f('ix_rolls_color_id'), table_name='rolls')
    op.drop_table('rolls')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_sku_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_order_items_sku_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_fy_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_batch_processing_value_addition_id'), table_name='batch_processing')
    op.drop_index(op.f('ix_batch_processing_status'), table_name='batch_processing')
    op.drop_index(op.f('ix_batch_processing_batch_id'), table_name='batch_processing')
    op.drop_index(op.f('ix_batch_processing_batch_challan_id'), table_name='batch_processing')
    op.drop_table('batch_processing')
    op.drop_index(op.f('ix_batch_assignments_tailor_id'), table_name='batch_assignments')
    op.drop_index(op.f('ix_batch_assignments_batch_id'), table_name='batch_assignments')
    op.drop_table('batch_assignments')
    op.drop_index(op.f('ix_supplier_invoices_supplier_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_sr_no'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_invoice_no'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_fy_id'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_source'), table_name='orders')
    op.drop_index(op.f('ix_orders_fy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_ledger_ref', table_name='ledger_entries')
    op.drop_index('ix_ledger_party', table_name='ledger_entries')
    op.drop_index('ix_ledger_fy', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_sku_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_size'), table_name='batches')
    op.drop_index(op.f('ix_batches_lot_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('user_companies', schema='public')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index(op.f('ix_lots_sku_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_job_challans_va_party_id'), table_name='job_challans')
    op.drop_index(op.f('ix_job_challans_status'), table_name='job_challans')
    op.drop_index(op.f('ix_job_challans_challan_no'), table_name='job_challans')
    op.drop_table('job_challans')
    op.drop_table('inventory_state')
    op.drop_table('financial_years')
    op.drop_index(op.f('ix_batch_challans_value_addition_id'), table_name='batch_challans')
    op.drop_index(op.f('ix_batch_challans_va_party_id'), table_name='batch_challans')
    op.drop_index(op.f('ix_batch_challans_status'), table_name='batch_challans')
    op.drop_index(op.f('ix_batch_challans_challan_no'), table_name='batch_challans')
    op.drop_table('batch_challans')
    op.drop_index(op.f('ix_skus_color_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_value_additions_short_code'), table_name='value_additions')
    op.drop_table('value_additions')
    op.drop_table('va_parties')
    op.drop_table('suppliers')
    op.drop_table('roles', schema='public')
    op.drop_table('companies', schema='public')
    op.drop_index(op.f('ix_product_types_code'), table_name='product_types')
    op.drop_table('product_types')
    op.drop_index(op.f('ix_fabrics_code'), table_name='fabrics')
    op.drop_table('fabrics')
    op.drop_table('customers')
    op.drop_index(op.f('ix_colors_color_no'), table_name='colors')
    op.drop_index(op.f('ix_colors_code'), table_name='colors')
    op.drop_table('colors')
    # ### end Alembic commands ###
