"""initial_schema_v2

Revision ID: d865522310db
Revises: 
Create Date: 2026-02-16 21:20:37.548036
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd865522310db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('skus',
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skus')),
    sa.UniqueConstraint('sku_code', name=op.f('uq_skus_sku_code'))
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('gst_no', sa.String(length=15), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('inventory_state',
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('total_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_inventory_state_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_state')),
    sa.UniqueConstraint('sku_id', name=op.f('uq_inventory_state_sku_id'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('lots',
    sa.Column('lot_code', sa.String(length=50), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('lot_date', sa.Date(), nullable=False),
    sa.Column('design_no', sa.String(length=50), nullable=False),
    sa.Column('standard_palla_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('default_size_pattern', sa.JSON(), nullable=False),
    sa.Column('pieces_per_palla', sa.Integer(), nullable=False),
    sa.Column('total_pallas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_pieces', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lots_created_by_users')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_lots_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lots')),
    sa.UniqueConstraint('lot_code', name=op.f('uq_lots_lot_code'))
    )
    op.create_index(op.f('ix_lots_sku_id'), 'lots', ['sku_id'], unique=False)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_order_ref', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_orders_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('rolls',
    sa.Column('roll_code', sa.String(length=50), nullable=False),
    sa.Column('fabric_type', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('remaining_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='kg', nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='in_stock', nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=50), nullable=True),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_rolls_received_by_users')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_rolls_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rolls')),
    sa.UniqueConstraint('roll_code', name=op.f('uq_rolls_roll_code'))
    )
    op.create_table('batches',
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('piece_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('color_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_qty', sa.Integer(), nullable=True),
    sa.Column('rejected_qty', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_batches_created_by_users')),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_batches_lot_id_lots')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_batches_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('batch_code', name=op.f('uq_batches_batch_code'))
    )
    op.create_index(op.f('ix_batches_lot_id'), 'batches', ['lot_id'], unique=False)
    op.create_index(op.f('ix_batches_sku_id'), 'batches', ['sku_id'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('inventory_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('roll_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_inventory_events_performed_by_users')),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_inventory_events_roll_id_rolls')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_inventory_events_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_inventory_events_event_id'))
    )
    op.create_index(op.f('ix_inventory_events_event_type'), 'inventory_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_inventory_events_performed_at'), 'inventory_events', ['performed_at'], unique=False)
    op.create_index(op.f('ix_inventory_events_sku_id'), 'inventory_events', ['sku_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invoices_created_by_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_table('lot_rolls',
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('roll_id', sa.Uuid(), nullable=False),
    sa.Column('palla_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('num_pallas', sa.Integer(), nullable=False),
    sa.Column('weight_used', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('waste_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('size_pattern', sa.JSON(), nullable=True),
    sa.Column('pieces_from_roll', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], name=op.f('fk_lot_rolls_lot_id_lots')),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_lot_rolls_roll_id_rolls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot_rolls'))
    )
    op.create_index(op.f('ix_lot_rolls_lot_id'), 'lot_rolls', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_rolls_roll_id'), 'lot_rolls', ['roll_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fulfilled_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_order_items_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_table('reservations',
    sa.Column('reservation_code', sa.String(length=50), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('external_order_ref', sa.String(length=100), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reservations_order_id_orders')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_reservations_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('reservation_code', name=op.f('uq_reservations_reservation_code'))
    )
    op.create_index(op.f('ix_reservations_sku_id'), 'reservations', ['sku_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_table('roll_processing',
    sa.Column('roll_id', sa.Uuid(), nullable=False),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_phone', sa.String(length=20), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('weight_before', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('weight_after', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('length_before', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('length_after', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processing_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_roll_processing_roll_id_rolls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roll_processing'))
    )
    op.create_table('batch_assignments',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('tailor_id', sa.Uuid(), nullable=False),
    sa.Column('checker_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_batch_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_assignments_batch_id_batches')),
    sa.ForeignKeyConstraint(['checker_id'], ['users.id'], name=op.f('fk_batch_assignments_checker_id_users')),
    sa.ForeignKeyConstraint(['tailor_id'], ['users.id'], name=op.f('fk_batch_assignments_tailor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_assignments'))
    )
    op.create_table('batch_roll_consumption',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('roll_id', sa.Uuid(), nullable=False),
    sa.Column('pieces_cut', sa.Integer(), nullable=False),
    sa.Column('length_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_by', sa.Uuid(), nullable=True),
    sa.Column('cut_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_roll_consumption_batch_id_batches')),
    sa.ForeignKeyConstraint(['cut_by'], ['users.id'], name=op.f('fk_batch_roll_consumption_cut_by_users')),
    sa.ForeignKeyConstraint(['roll_id'], ['rolls.id'], name=op.f('fk_batch_roll_consumption_roll_id_rolls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_roll_consumption'))
    )
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_invoice_items_batch_id_batches')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_invoice_items_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('batch_roll_consumption')
    op.drop_table('batch_assignments')
    op.drop_table('roll_processing')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_sku_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_lot_rolls_roll_id'), table_name='lot_rolls')
    op.drop_index(op.f('ix_lot_rolls_lot_id'), table_name='lot_rolls')
    op.drop_table('lot_rolls')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_events_sku_id'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_performed_at'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_event_type'), table_name='inventory_events')
    op.drop_table('inventory_events')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_sku_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_lot_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('rolls')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index(op.f('ix_lots_sku_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_table('users')
    op.drop_table('inventory_state')
    op.drop_table('suppliers')
    op.drop_table('skus')
    op.drop_table('roles')
    # ### end Alembic commands ###
