"""S125: Polymorphic PaymentAllocation + amount_paid on SI/JC/BC.

Phase 2 of PAYMENTS_AND_ALLOCATIONS_PLAN — extends bill-wise payment recording
to supplier (SupplierInvoice) and va_party (JobChallan + BatchChallan) bills.

Schema changes (per tenant schema co_*):
  payment_allocations
    + bill_type VARCHAR(30)  (NULL during transition, NOT NULL after backfill)
    + bill_id UUID
    drop FK invoice_id → invoices(id)
    drop column invoice_id
    + CHECK pa_valid_bill_type
    + indexes ix_pa_receipt_bill / ix_pa_bill
  supplier_invoices
    + amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0
  job_challans
    + amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0
  batch_challans
    + amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0

Backfill:
  Production state verified 2026-04-27: 0 payment_receipts, 0 payment_allocations,
  12 supplier_invoices, 0 challans. The polymorphic refactor is therefore
  destructive only on tables that have no rows yet — safe to ALTER without
  data preservation.

Idempotent. Round-trip safe (downgrade reverses cleanly).

Revision ID: p6q7r8s9t0u1
Revises: o5p6q7r8s9t0
Create Date: 2026-04-27
"""
from alembic import op
from sqlalchemy import text

from migrations.tenant_utils import (
    col_exists,
    constraint_exists,
    get_tenant_schemas,
    index_exists,
)

revision = "p6q7r8s9t0u1"
down_revision = "o5p6q7r8s9t0"
branch_labels = None
depends_on = None


def _fk_exists(conn, schema: str, table: str, fk_name: str) -> bool:
    r = conn.execute(text(
        f"SELECT 1 FROM information_schema.table_constraints "
        f"WHERE table_schema='{schema}' AND table_name='{table}' "
        f"AND constraint_name='{fk_name}' AND constraint_type='FOREIGN KEY'"
    ))
    return r.fetchone() is not None


def upgrade():
    conn = op.get_bind()
    for s in get_tenant_schemas(conn):

        # 1. amount_paid on SI / JC / BC
        for table in ("supplier_invoices", "job_challans", "batch_challans"):
            if not col_exists(conn, s, table, "amount_paid"):
                conn.execute(text(
                    f"ALTER TABLE {s}.{table} "
                    f"ADD COLUMN amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0"
                ))

        # 2. payment_allocations: add bill_type + bill_id
        if not col_exists(conn, s, "payment_allocations", "bill_type"):
            conn.execute(text(
                f"ALTER TABLE {s}.payment_allocations "
                f"ADD COLUMN bill_type VARCHAR(30)"
            ))
        if not col_exists(conn, s, "payment_allocations", "bill_id"):
            conn.execute(text(
                f"ALTER TABLE {s}.payment_allocations "
                f"ADD COLUMN bill_id UUID"
            ))

        # 3. Backfill any existing rows: copy invoice_id → bill_id with
        # bill_type='invoice'. Production has 0 rows but still safe.
        if col_exists(conn, s, "payment_allocations", "invoice_id"):
            conn.execute(text(f"""
                UPDATE {s}.payment_allocations
                SET bill_type = 'invoice', bill_id = invoice_id
                WHERE bill_id IS NULL AND invoice_id IS NOT NULL
            """))

            # 4. Drop FK + drop legacy invoice_id column + drop legacy index
            #    (FK constraint name is auto-generated by Alembic — find by table)
            r = conn.execute(text(
                f"SELECT constraint_name FROM information_schema.table_constraints "
                f"WHERE table_schema='{s}' AND table_name='payment_allocations' "
                f"AND constraint_type='FOREIGN KEY'"
            ))
            for row in r.fetchall():
                fk_name = row[0]
                # Only drop FKs that reference invoices, leave receipt FK intact
                # (named via column suffix in PG default convention).
                if "invoice" in fk_name and "receipt" not in fk_name:
                    conn.execute(text(
                        f"ALTER TABLE {s}.payment_allocations DROP CONSTRAINT {fk_name}"
                    ))
            if index_exists(conn, s, "ix_payment_allocations_invoice_id"):
                conn.execute(text(
                    f"DROP INDEX {s}.ix_payment_allocations_invoice_id"
                ))
            if index_exists(conn, s, "ix_pa_receipt_invoice"):
                conn.execute(text(
                    f"DROP INDEX {s}.ix_pa_receipt_invoice"
                ))
            conn.execute(text(
                f"ALTER TABLE {s}.payment_allocations DROP COLUMN invoice_id"
            ))

        # 5. Tighten new columns to NOT NULL
        conn.execute(text(
            f"ALTER TABLE {s}.payment_allocations "
            f"ALTER COLUMN bill_type SET NOT NULL"
        ))
        conn.execute(text(
            f"ALTER TABLE {s}.payment_allocations "
            f"ALTER COLUMN bill_id SET NOT NULL"
        ))

        # 6. Add CHECK constraint for valid bill types
        if not constraint_exists(conn, s, "pa_valid_bill_type"):
            conn.execute(text(f"""
                ALTER TABLE {s}.payment_allocations
                ADD CONSTRAINT pa_valid_bill_type
                CHECK (bill_type IN ('invoice', 'supplier_invoice', 'job_challan', 'batch_challan'))
            """))

        # 7. Indexes for the new polymorphic shape
        if not index_exists(conn, s, "ix_pa_receipt_bill"):
            conn.execute(text(
                f"CREATE INDEX ix_pa_receipt_bill "
                f"ON {s}.payment_allocations (payment_receipt_id, bill_type, bill_id)"
            ))
        if not index_exists(conn, s, "ix_pa_bill"):
            conn.execute(text(
                f"CREATE INDEX ix_pa_bill "
                f"ON {s}.payment_allocations (bill_type, bill_id)"
            ))


def downgrade():
    conn = op.get_bind()
    for s in get_tenant_schemas(conn):

        # 1. Drop new indexes + constraint
        if index_exists(conn, s, "ix_pa_bill"):
            conn.execute(text(f"DROP INDEX {s}.ix_pa_bill"))
        if index_exists(conn, s, "ix_pa_receipt_bill"):
            conn.execute(text(f"DROP INDEX {s}.ix_pa_receipt_bill"))
        if constraint_exists(conn, s, "pa_valid_bill_type"):
            conn.execute(text(
                f"ALTER TABLE {s}.payment_allocations DROP CONSTRAINT pa_valid_bill_type"
            ))

        # 2. Re-add invoice_id, backfill from rows where bill_type='invoice'
        if not col_exists(conn, s, "payment_allocations", "invoice_id"):
            conn.execute(text(
                f"ALTER TABLE {s}.payment_allocations ADD COLUMN invoice_id UUID"
            ))
        conn.execute(text(f"""
            UPDATE {s}.payment_allocations
            SET invoice_id = bill_id
            WHERE bill_type = 'invoice'
        """))
        # Rows for non-invoice bills become orphans — accept the data loss
        # (downgrade is a recovery hatch only).
        conn.execute(text(
            f"DELETE FROM {s}.payment_allocations WHERE bill_type <> 'invoice'"
        ))
        conn.execute(text(
            f"ALTER TABLE {s}.payment_allocations "
            f"ALTER COLUMN invoice_id SET NOT NULL"
        ))
        conn.execute(text(f"""
            ALTER TABLE {s}.payment_allocations
            ADD CONSTRAINT payment_allocations_invoice_id_fkey
            FOREIGN KEY (invoice_id) REFERENCES {s}.invoices(id) ON DELETE RESTRICT
        """))
        if not index_exists(conn, s, "ix_payment_allocations_invoice_id"):
            conn.execute(text(
                f"CREATE INDEX ix_payment_allocations_invoice_id "
                f"ON {s}.payment_allocations (invoice_id)"
            ))
        if not index_exists(conn, s, "ix_pa_receipt_invoice"):
            conn.execute(text(
                f"CREATE INDEX ix_pa_receipt_invoice "
                f"ON {s}.payment_allocations (payment_receipt_id, invoice_id)"
            ))

        # 3. Drop polymorphic columns
        if col_exists(conn, s, "payment_allocations", "bill_id"):
            conn.execute(text(
                f"ALTER TABLE {s}.payment_allocations DROP COLUMN bill_id"
            ))
        if col_exists(conn, s, "payment_allocations", "bill_type"):
            conn.execute(text(
                f"ALTER TABLE {s}.payment_allocations DROP COLUMN bill_type"
            ))

        # 4. Drop amount_paid columns
        for table in ("batch_challans", "job_challans", "supplier_invoices"):
            if col_exists(conn, s, table, "amount_paid"):
                conn.execute(text(
                    f"ALTER TABLE {s}.{table} DROP COLUMN amount_paid"
                ))
